import type { Metadata } from "next";
import "./globals.css";
import { montseratt } from "@/app/ui/fonts";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Nextmas Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montseratt.className}`}>
        <div className="m-auto max-w-360">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
